name: Automatically update terraform.nuspec
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
on:
  create:
  workflow_dispatch:

jobs:
    job1:
      name: "dependabot-auto-update"
      runs-on: windows-latest
      if: ${{ startsWith(github.ref, 'refs/heads/dependabot/') }}
      steps:
        - uses: actions/checkout@v4

        - name: Install AU Module
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module AU 
            Get-Module AU -ListAvailable

        - name: build package
          shell: pwsh
          working-directory: ./terraform
          run: ./update.ps1

        - name: Configure git
          working-directory: ./terraform
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
        
        - name: Commit and push changes to terraform.nuspec
          working-directory: ./terraform
          run: |
              git add terraform.nuspec
              git commit -m "[dependabot skip] Update terraform.nuspec"
              git push origin ${{ github.head_ref }}

    job2:
      name: "renovate-auto-update"
      runs-on: windows-latest
      if: ${{ startsWith(github.ref, 'refs/heads/renovate/') }}
      steps:
        - uses: actions/checkout@v4

        - name: Install AU Module
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module AU 
            Get-Module AU -ListAvailable

        - name: build package
          shell: pwsh
          working-directory: ./terraform
          run: ./update.ps1

        - name: Configure git
          working-directory: ./terraform
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
        
        - name: Commit and push changes to terraform.nuspec
          working-directory: ./terraform
          run: |
              git add terraform.nuspec
              git commit -m "Update terraform.nuspec"
              git push origin ${{ github.head_ref }}

    job3:
      name: "user-update"
      runs-on: windows-latest
      if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
      steps:
        - uses: actions/checkout@v4

        - name: Install AU Module
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module AU 
            Get-Module AU -ListAvailable

        - name: build package
          shell: pwsh
          working-directory: ./terraform
          run: ./update.ps1

        - name: Configure git
          working-directory: ./terraform
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
        
        - name: Commit changes to terraform.nuspec
          working-directory: ./terraform
          run: |
              git add terraform.nuspec
              git commit -m "Update terraform.nuspec"
              git push origin ${{ github.head_ref }}
